### ISSUE TITLE
grayed out and missing icons 

### ISSUE THREAD

**Issue by avatar7652** [CutFlame/MCDSaveEdit#22]
![Screenshot (3)](https://user-images.githubusercontent.com/73441753/105636896-8061ba80-5e38-11eb-9e13-be9be0a7955b.png)

**Comment by CutFlame** [comment]
This means it couldn't find the .pak files from the Minecraft: Dungeons installation. Try using the "Game Paks" menu item to specify where the .pak files are. The default location is "%localappdata%\AppData\Local\Mojang\products\dungeons\dungeons\Dungeons\Content\Paks". If you have the windows store version of Minecraft: Dungeons then you need to run the storepatcher.exe for it to extract the .pak files.

**Comment by lordferky** [comment]
i use the storepatcher.ps1 because i cant find any storepatcher.exe and i cant still see the images

**Comment by okibcn** [comment]
It is not an issue with the folder location. It happened since the nether update. Maybe the code need an update to work properly with Minecraft Dungeons 1.8 update..

dtools can properly convert savegame file between dat<->json.

**Comment by CutFlame** [comment]
Try the latest version. I just released 1.3.0:
https://github.com/CutFlame/MCDSaveEdit/releases/tag/release%2F1.3.0

**Comment by Jim-Zenn** [comment]
This issue persists in 1.3.0, with Minecraft Launcher version, and the patch doesn't work.
