### ISSUE TITLE
Save Editor Doesn't Work

### ISSUE THREAD

**Issue by kran27** [CutFlame/MCDSaveEdit#3]
I keep getting the error "File was not in an expected format"

**Comment by CutFlame** [comment]
I have published a new version that has better parsing of the files. Please try again with this new version.

**Comment by kran27** [comment]
Still doesn't work
![Save this file as .dat, GitHub only supports like 5 filetypes](https://user-images.githubusercontent.com/56488228/96228335-4dab4a80-0f4a-11eb-8f70-f073c17fb946.jpg)

**Comment by CutFlame** [comment]
The issue ended up being that your currency value was too high and couldn't be interpreted correctly. I have published a new version that supports higher numbers. Thank you for helping me find bugs!
